name: Label check
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          any_of: breaking,new feature,enhancement,visual,documentation,bug,deprecation,internal,dependencies,skip-release,release,no label
          repo_token: ${{ secrets.GITHUB_TOKEN }}
