name: Cron

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "30 21 * * 1-5"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-version:
    name: Check version
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event.schedule && github.event.inputs.mode != 'force-version' && github.event.inputs.version != '' }}
        run: |
          echo "::error::Please choose version mode when forcing a version number"
          exit 1
      - if: ${{ github.event.schedule && github.event.inputs.mode == 'force-version' && github.event.inputs.version == '' }}
        run: |
          echo "::error::Please enter a version number when forcing a specific publish version"
          exit 1

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
  
      - run: |
          test "$(npx auto version)" != "patch" && exit 0 || exit 1

      - run: |
          test "$(npx auto version)" != "major" && exit 0 || exit 1

  build:
    name: Node v${{ matrix.node }}
    if: ${{ github.event.schedule || github.event.inputs.mode == 'publish' || github.event.inputs.mode == 'force-version' || (github.event_name == 'push' && github.ref_name == 'master') }}
    needs: check-version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
