name: PR check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          any_of: breaking,new feature,enhancement,visual,documentation,bug,deprecation,internal,dependencies,skip-release,release
          repo_token: ${{ secrets.GITHUB_TOKEN }}
  check_branch:
    name: Check branch
    needs: check_labels
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
      - name: Run JS script
        run: |
          node check-branch.js
