on:
  cron: "0 10 * * 1-5" # 10am Mon-Fri
  workflow_dispatch:

jobs:
  test-group-by-job:
    name: Group By
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.group-by.outputs.matrix }}
    steps:
      - name: Testing dependaction group by
        id: group-by
        uses: rgdelato/dependaction-group-by@v0.0.0-25
        with:
          directories: "" # e.g. Clients/Web,Clients/Mobile
          exclude-packages: |
            @types/jquery
            @types/knockout
            jquery
            knockout
            resumablejs
          limit: 5
  test-create-pr-job:
    name: Create Pull Request
    runs-on: ubuntu-latest
    needs: test-group-by-job
    if: always()
    strategy:
      matrix: ${{ fromJson(needs.test-group-by-job.outputs.matrix) }}
    steps:
      - uses: rgdelato/dependaction-create-pull-requests@v0.0.0-13
        with:
          matrix: ${{ toJson(matrix) }}
          install-command: npm run bootstrap
          reviewers-major: servicetitan/frontend-platform-dependabot-reviewers
          reviewers-minor: sistr
          reviewers-patch: sistr
          labels: |
            dependencies
            bot
