on: [push, workflow_dispatch]

jobs:
  test-group-by-job:
    runs-on: ubuntu-latest
    name: A job to say hello
    outputs:
      matrix: ${{ steps.group-by.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
      - name: Testing dependaction group by
        id: group-by
        uses: rgdelato/dependaction-group-by@v0.0.0-20
        with:
          directories: ""
          exclude-packages: jquery
          limit: 5
      # Use the output from the `hello` step
      - name: Debug output
        run: echo 'Group by ${{ steps.group-by.outputs.matrix }}'
  test-create-pr-job:
    if: always()
    needs: test-group-by-job
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.test-group-by-job.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
      - name: Debug matrix
      run: echo 'Matrix ${{ toJson(matrix) }}'
