name: Create PRs (Dependaction)

on:
  # schedule:
  #   - cron: "0 18 * * 1-5" # 10am Mon-Fri
  workflow_dispatch:
    inputs:
      limit:
        default: 1
        required: false
        type: string

jobs:
  test-group-by-job:
    name: Group By
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.group-by.outputs.matrix }}
    steps:
      - name: Testing dependaction group by
        id: group-by
        uses: rgdelato/dependaction-group-by@v0.0.3
        with:
          directories: "" # e.g. Clients/Web,Clients/Mobile
          exclude-packages: |
            @docusaurus/*
            @types/jquery
            @types/knockout
            jquery
            knockout
            resumablejs
          limit: ${{ github.event.inputs.limit }}
  test-create-pr-job:
    name: Create Pull Request
    if: always()
    needs: test-group-by-job
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.test-group-by-job.outputs.matrix) }}
    steps:
      - uses: rgdelato/dependaction-create-pull-requests@v0.0.6-15
        with:
          token: ${{ secrets.PAT }}
          matrix: ${{ toJson(matrix) }}
          install-command: npm run bootstrap
          reviewers-major: rgdelato
          assignees-minor: rgdelato
          assignees-patch: rgdelato
          labels: |
            dependencies
