on: [push, workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
      - name: Testing dependaction group by
        id: group-by
        uses: rgdelato/dependaction-group-by@v0.0.0-19
        with:
          directories: ""
          exclude-packages: jquery
          limit: 5
      # Use the output from the `hello` step
      - name: Debug output
        run: echo "Group by returned ${{ steps.group-by.outputs.matrix }}"
      - name: Hello world action step
        id: hello
        uses: rgdelato/hello-world-javascript-action@v1.1
        with:
          who-to-greet: "Mona the Octocat"
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
