name: "Nightly Merge"

# on:
#   push:
#     branches:
#       - master

on:
  workflow_dispatch:

jobs:
  nightly-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Merge master to rc
        uses: robotology/gh-action-nightly-merge@v1.4.0
        with:
          stable_branch: "master"
          development_branch: "rc"
          allow_ff: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.create({
              owner: "rgdelato",
              repo: "hello-world-using-action",
              title: "Merge master branch to rc branch",
              head: "master",
              base: "rc",
              body: "Does this work?"
            })
