name: Rebase (Dependaction)
# on:
#   push:
#     branches: [master]
jobs:
  test-rebase:
    name: Rebase
    runs-on: ubuntu-latest
    steps:
      - name: Rebase
        id: rebase
        uses: rgdelato/dependaction-rebase@v0.0.1-1
        with:
          token: ${{ secrets.PAT }}
          base-branch: master
